### ISSUE TITLE
Messages wont update when price total does

### ISSUE THREAD

**Issue by lancemccluskey** [paypal/paypal-messaging-components#477]
I got the initial messages to render by rendering at the top of the slide in cart, and then moving the html container to the bottom of the cart. However, when the cart total updates the messages disappear and I get the old console warnings about the container being 0px by 0px.

https://user-images.githubusercontent.com/40124399/113141567-79b44280-91ef-11eb-98a3-b98adf770a79.mp4

**Comment by Seavenly** [comment]
Hi @lancemccluskey 

I believe this may have to do with a lack of content on the webpage, where our library is likely attempting to use the `body` as the boundary and the message is outside that boundary because of the `fixed` side cart. 

Would you be able to pull down my branch with changes and see if that addresses your issue? You'll want to use `npm run dev:standalone` to run our messages locally with the webpack dev server and then look at `/demo/standalone.html` to see the `<script>` include you'll need to substitute on your page instead of the sandbox url.

https://github.com/Seavenly/paypal-messaging-components/tree/improve-overflow-detection-2

**Comment by lancemccluskey** [comment]
Yeah I'll try it out. Thanks!

**Comment by lancemccluskey** [comment]
Are there specific query parameters i need to provide/remove when using a localhost address?

**Comment by Seavenly** [comment]
You'll need to change the address from `localhost.paypal.com` to just `localhost`. You'll also want to ensure that you are using the `data-pp-account` attribute on the script instead of a client-id in the url as we have local fake accounts we use for development.

I think this should hopefully work for you:
``` HTML
<script src="https://localhost:8080/messaging.js" data-pp-account="DEV000000GPLQ"></script>
```

**Comment by lancemccluskey** [comment]
hmm still getting connection refused. I dont need to pass any query parameters right?

![Screen Shot 2021-03-31 at 3 28 48 PM](https://user-images.githubusercontent.com/40124399/113207070-cd497f00-9235-11eb-9e25-698d6b7ab647.png)

**Comment by Seavenly** [comment]
You may need to open that request in a new tab and accept the security warnings because the webpack dev server is using a self-signed cert.

**Comment by lancemccluskey** [comment]
Ok I got that part fixed, but now im seeing this when the page loads. I logged the `Messages` function so its getting loaded properly.

![Screen Shot 2021-04-01 at 9 00 54 AM](https://user-images.githubusercontent.com/40124399/113305545-c586ea80-92c8-11eb-9d22-f72ed518baac.png)

**Comment by Seavenly** [comment]
Inside of `/utils/devServerProxy/proxy.js` you'll want to change all instances of `localhost.paypal.com` to just `localhost`. And the same thing for `/globals.js`.

**Comment by Seavenly** [comment]
@lancemccluskey Were you able to confirm whether or not the fix addressed the issue you were seeing?

**Comment by lancemccluskey** [comment]
No I wasn't able to get it running locally, but we decided to just move forward with the default messaging (not providing the Cart total). Sorry I forgot to let you know last week, I've been on PTO
